# version: '3.8'
services:
  dreamidiarynextjs:
    image: dreamidiarynextjs-image
    container_name: dreamidiarynextjs-container
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
